package com.moilioncircle.ddl.parser;

public enum DataType {
    DEFAULT, BIT, TINYINT, SMALLINT, MEDIUMINT, INTEGER, REAL, DOUBLE, FLOAT, DECIMAL, NUMERIC,
    DATE, TIME, TIMESTAMP, DATETIME, YEAR, CHAR, VARCHAR, BINARY, TINYBLOB, BLOB, MEDIUMBLOB, LONGBLOB,
    TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT, ENUM, SET, INT, BIGINT, VARBINARY;
}
